from setuptools import setup

setup(name='cmo',
        version='0.6',
        description='Center for Molecular Oncology Python Package for Great Convenience and Enhanced Double Plus User Experiences',
        url='github.com/mskcc/mskcmo.git',
        author='Chris Harris',
        author_email='harrisc2@mskcc.org',
        licence='GPLv3',
        packages=['cmo'],
        install_requires=['argparse', 'fireworks', 'python-daemon', 'filemagic'],
        scripts=['bin/cmo_bwa_sampe',
                 'bin/cmo_getbasecounts',
                 'bin/cmo_facets',
                 'bin/cmoflow_facets',
                 'bin/cmoflow_postprocess',
                 'bin/cmo_bwa_aln',
                 'bin/cmo_watcher',
                 'bin/cmo_bwa_mem',
                 'bin/cmo_picard',
                 'bin/cmo_gatk',
                 'bin/cmo_mutect',
                 'bin/cmo_bedtools',
                 'bin/cmo_maf2maf',
                 'bin/cmo_vcf2maf',
                 'bin/cmo_maf2vcf',
                 'bin/cmo_filter_haplotype',
                 'bin/cmo_filter_mutect',
                 'bin/cmo_merge_mafs',
                 'bin/cmo_trinuc_and_impact',
                 'bin/cmo_add_variant_info',
                 'bin/cmo_mutsig',
                 'bin/cmo_make_facets_file',
                 'bin/cmo_abra'
                 ],
        zip_safe=False)

