#!/opt/common/CentOS_6-dev/python/python-2.7.10/bin/python

import cmo

task1 = cmo.workflow.Job('echo "Ingrid is the CEO"', name="Task1")
task2 = cmo.workflow.Job('echo "Jill is a manager."', name="Task2")
task3 = cmo.workflow.Job('echo "Jack is a manager."', name="Task3")
task4 = cmo.workflow.Job('echo "Kip is an intern."', name="Task4")

# assemble Workflow from FireWorks and their connections by id
jobs_list = [task1,task2,task3,task4]
print vars(task1)
jobs_dict = {task1: [task2,task3], task2: [task4], task3:[task4]}
new_workflow = cmo.workflow.Workflow(jobs_list, jobs_dict)
new_workflow.run('serial')



