#!/opt/common/CentOS_6-dev/python/python-2.7.10/bin/python

import cmo
from cmo import workflow
task1 = workflow.Job('echo "Ingrid is the CEO"', name="Task 1", queue="test")
task2 = workflow.Job('echo "Jill is a manager."', name="Task 2", queue="test")
task3 = workflow.Job('echo "Jack is a manager."', name="Task 3", queue="test")
task4 = workflow.Job('echo "Kip is an intern."', name="Task 4", queue="test")

# assemble Workflow from FireWorks and their connections by id
jobs_list = [task1,task2,task3,task4]
jobs_dict = {task1: [task2,task3], task2: [task4], task3:[task4]}
new_workflow = workflow.Workflow(jobs_list, jobs_dict, name="Test LSF Workflow")
new_workflow.run('LSF', daemon_log="test")



